<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Simulation/**/*.cs" />
    <Compile Remove="LeaderGame.Core/**/*.cs" />
    <Compile Remove="LeaderGame.Desktop/**/*.cs" />
    <Compile Remove="LeaderGame.Tests/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="LeaderGame.Core/LeaderGame.Core.csproj" />
  </ItemGroup>

</Project>
